In [1]:
import numpy as np

def compare_homographies(H1, H2, points):
    """
    Compare two homography matrices by various metrics.
    
    Args:
    H1, H2: Homography matrices to compare.
    points: A set of points to test the homographies on.
    
    Returns:
    A dictionary with various comparison metrics.
    """
    # Ensure H1 and H2 are numpy arrays
    H1 = np.array(H1)
    H2 = np.array(H2)
    
    # Compute the difference matrix
    diff = H1 - H2
    
    # Frobenius norm of the difference
    frobenius_norm = np.linalg.norm(diff, 'fro')
    
    # Mean Absolute Error (MAE)
    mae = np.mean(np.abs(diff))
    
    # Maximum Absolute Error (MaxAE)
    max_ae = np.max(np.abs(diff))
    
    # Transform the points using both homographies
    points = np.concatenate([points, np.ones((points.shape[0], 1))], axis=1)  # Add ones for homogeneous coordinates
    points_H1 = (H1 @ points.T).T
    points_H1 /= points_H1[:, 2][:, np.newaxis]
    
    points_H2 = (H2 @ points.T).T
    points_H2 /= points_H2[:, 2][:, np.newaxis]
    
    # Compute reprojection error
    reprojection_error = np.linalg.norm(points_H1 - points_H2, axis=1).mean()
    
    # Summary of differences
    comparison_results = {
        "frobenius_norm": frobenius_norm,
        "mean_absolute_error": mae,
        "max_absolute_error": max_ae,
        "difference_matrix": diff,
        "reprojection_error": reprojection_error
    }
    
    return comparison_results

In [12]:
# image 1 and image 2 DETR
H1 = np.array([[ 6.48527287e-01,  1.10006708e-02,  1.19024450e+03],
 [-2.44472274e-01,  9.15187134e-01,  1.44702351e+02],
 [-1.44055274e-04,  3.59894735e-06,  1.00000000e+00]])
H2 = np.array([[ 6.47289063e-01,  1.09398204e-02,  1.19005325e+03],
 [-2.45172143e-01,  9.14543683e-01,  1.45369579e+02],
 [-1.44495926e-04,  3.44534677e-06,  1.00000000e+00]])
points = np.array([[100, 200], [300, 400], [500, 600], [700, 800]])

comparison_results = compare_homographies(H1, H2, points)

print("Comparison Results:")
for key, value in comparison_results.items():
    print(f"{key}: {value}")

Comparison Results:
frobenius_norm: 0.6940981250741811
mean_absolute_error: 0.09568010985029513
max_absolute_error: 0.6672279999999944
difference_matrix: [[ 1.2382240e-03  6.0850400e-05  1.9125000e-01]
 [ 6.9986900e-04  6.4345100e-04 -6.6722800e-01]
 [ 4.4065200e-07  1.5360058e-07  0.0000000e+00]]
reprojection_error: 0.4314189003753385


In [13]:
# image 1 and image 2 SETR
H1 = np.array([[ 6.48527287e-01,  1.10006708e-02,  1.19024450e+03],
 [-2.44472274e-01,  9.15187134e-01,  1.44702351e+02],
 [-1.44055274e-04,  3.59894735e-06,  1.00000000e+00]])
H2 = np.array([[ 6.47289063e-01,  1.09398204e-02,  1.19005325e+03],
 [-2.45172143e-01,  9.14543683e-01,  1.45369579e+02],
 [-1.44495926e-04,  3.44534677e-06,  1.00000000e+00]])
points = np.array([[100, 200], [300, 400], [500, 600], [700, 800]])

comparison_results = compare_homographies(H1, H2, points)

print("Comparison Results:")
for key, value in comparison_results.items():
    print(f"{key}: {value}")

Comparison Results:
frobenius_norm: 0.6940981250741811
mean_absolute_error: 0.09568010985029513
max_absolute_error: 0.6672279999999944
difference_matrix: [[ 1.2382240e-03  6.0850400e-05  1.9125000e-01]
 [ 6.9986900e-04  6.4345100e-04 -6.6722800e-01]
 [ 4.4065200e-07  1.5360058e-07  0.0000000e+00]]
reprojection_error: 0.4314189003753385


In [14]:
# image 01 and image 02 DETR
H1 = np.array([[ 4.51757367e-01,  1.15429274e-02,  9.38065244e+02],
 [-2.43162047e-01,  9.58401398e-01, -2.54262009e+01],
 [-4.46051805e-04,  3.02287945e-05,  1.00000000e+00]])
H2 = np.array([[ 4.51757367e-01,  1.15429274e-02,  9.38065244e+02],
 [-2.43162047e-01,  9.58401398e-01, -2.54262009e+01],
 [-4.46051805e-04,  3.02287945e-05,  1.00000000e+00]])
points = np.array([[100, 200], [300, 400], [500, 600], [700, 800]])

comparison_results = compare_homographies(H1, H2, points)

print("Comparison Results:")
for key, value in comparison_results.items():
    print(f"{key}: {value}")

Comparison Results:
frobenius_norm: 0.0
mean_absolute_error: 0.0
max_absolute_error: 0.0
difference_matrix: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
reprojection_error: 0.0


In [15]:
# image 01 and image 02 SETR
H1 = np.array([[ 4.51757367e-01,  1.15429274e-02,  9.38065244e+02],
 [-2.43162047e-01,  9.58401398e-01, -2.54262009e+01],
 [-4.46051805e-04,  3.02287945e-05,  1.00000000e+00]])
H2 = np.array([[ 4.51757367e-01,  1.15429274e-02,  9.38065244e+02],
 [-2.43162047e-01,  9.58401398e-01, -2.54262009e+01],
 [-4.46051805e-04,  3.02287945e-05,  1.00000000e+00]])
points = np.array([[100, 200], [300, 400], [500, 600], [700, 800]])

comparison_results = compare_homographies(H1, H2, points)

print("Comparison Results:")
for key, value in comparison_results.items():
    print(f"{key}: {value}")

Comparison Results:
frobenius_norm: 0.0
mean_absolute_error: 0.0
max_absolute_error: 0.0
difference_matrix: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
reprojection_error: 0.0


In [16]:
# image 001 and image 002 DETR
H1 = np.array([[ 7.65512704e-01,  3.84620713e-02,  4.46433809e+02],
 [-1.35721153e-01,  9.12837382e-01,  7.59893457e+01],
 [-2.11758694e-04, -3.08679558e-05,  1.00000000e+00]])
H2 = np.array([[ 7.65963430e-01,  3.75384919e-02,  4.46504361e+02],
 [-1.35239452e-01,  9.12002719e-01,  7.60726136e+01],
 [-2.10736151e-04, -3.21767955e-05,  1.00000000e+00]])
points = np.array([[100, 200], [300, 400], [500, 600], [700, 800]])

comparison_results = compare_homographies(H1, H2, points)

print("Comparison Results:")
for key, value in comparison_results.items():
    print(f"{key}: {value}")

Comparison Results:
frobenius_norm: 0.10914720668978654
mean_absolute_error: 0.017390322309190687
max_absolute_error: 0.08326789999999562
difference_matrix: [[-4.5072600e-04  9.2357940e-04 -7.0552000e-02]
 [-4.8170100e-04  8.3466300e-04 -8.3267900e-02]
 [-1.0225430e-06  1.3088397e-06  0.0000000e+00]]
reprojection_error: 0.030281455634759615


In [17]:
# image 001 and image 002 SETR
H1 = np.array([[ 7.65512704e-01,  3.84620713e-02,  4.46433809e+02],
 [-1.35721153e-01,  9.12837382e-01,  7.59893457e+01],
 [-2.11758694e-04, -3.08679558e-05,  1.00000000e+00]])
H2 = np.array([[ 7.65963430e-01,  3.75384919e-02,  4.46504361e+02],
 [-1.35239452e-01,  9.12002719e-01,  7.60726136e+01],
 [-2.10736151e-04, -3.21767955e-05,  1.00000000e+00]])
points = np.array([[100, 200], [300, 400], [500, 600], [700, 800]])

comparison_results = compare_homographies(H1, H2, points)

print("Comparison Results:")
for key, value in comparison_results.items():
    print(f"{key}: {value}")

Comparison Results:
frobenius_norm: 0.10914720668978654
mean_absolute_error: 0.017390322309190687
max_absolute_error: 0.08326789999999562
difference_matrix: [[-4.5072600e-04  9.2357940e-04 -7.0552000e-02]
 [-4.8170100e-04  8.3466300e-04 -8.3267900e-02]
 [-1.0225430e-06  1.3088397e-06  0.0000000e+00]]
reprojection_error: 0.030281455634759615
